# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGG5tS14H81bFg9tR_AA4-LQpg-rJV5n
"""

!pip install transformers torch datasets accelerate gradio

import gradio as gr
from transformers import pipeline

generator = pipeline('text-generation', model='gpt2')

def generate_text(prompt):
    results = generator(prompt, max_length=50, num_return_sequences=1)
    return results[0]['generated_text']

interface = gr.Interface(fn=generate_text, inputs="text", outputs="text", title="GPT-2 Text Generator", description="Enter a prompt and generate text using GPT-2.")

4interface.launch()

cd Gradio-kg